/**
 * Catálogo real de linhas de ônibus de São José dos Campos.
 *
 * Fonte oficial: Prefeitura de São José dos Campos - Secretaria de
 * Mobilidade Urbana, página "Transporte Coletivo - Horário e itinerário de
 * ônibus":
 * https://sjc.sp.gov.br/servicos/mobilidade-urbana/transporte-coletivo/
 * (lista consultada em 25/09/2026; ver o campo `sourceUrl` de cada linha
 * para o PDF oficial específico, publicado pela própria Prefeitura).
 *
 * Cada item abaixo é real: código e nome exatamente como publicados pela
 * Prefeitura, e o link do PDF oficial de horário/itinerário daquela linha.
 * NÃO inclui paradas, coordenadas ou horários — a Prefeitura publica essas
 * informações apenas dentro do PDF de cada linha, em uma tabela que não é
 * extraível de forma confiável como texto simples (ver README em
 * api/src/integrations/transit/). Popular paradas/horários "aproximados" a
 * partir disso seria inventar precisão que a fonte não garante, o que a
 * sprint pede para evitar.
 */
export const OFFICIAL_SJC_LINES: { code: string; name: string; sourceUrl: string }[] = [
  { code: 'LV', name: 'Linha Verde – Estação Sul/Centro e Estação Sul/Rodoviária', sourceUrl: 'https://sjc.sp.gov.br/media/jnxhxrvc/lv-05_site.pdf' },
  { code: '066', name: 'Eco Campos de São José / Av. João Rodolfo Castelli', sourceUrl: 'https://sjc.sp.gov.br/media/bkvfbpsj/066-04_site.pdf' },
  { code: '082', name: 'Estação Sul / Jd. das Colinas', sourceUrl: 'https://sjc.sp.gov.br/media/qhwaskuj/082-02_site.pdf' },
  { code: '101', name: 'Represa / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/spaelypb/101-48_site.pdf' },
  { code: '102', name: 'Alimentadora Jaguari / Vila Dirce', sourceUrl: 'https://sjc.sp.gov.br/media/24fnvjua/102-43_site.pdf' },
  { code: '103', name: 'Costinha / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/ztjn2bqp/103-66_site.pdf' },
  { code: '104', name: 'Alimentadora Vargem Grande / Alto da Ponte', sourceUrl: 'https://sjc.sp.gov.br/media/ojsfqelr/104-26_site.pdf' },
  { code: '105', name: 'Bairro dos Freitas / Av. Eng. Francisco José Longo', sourceUrl: 'https://sjc.sp.gov.br/media/ep1penwg/105-59_site-1.pdf' },
  { code: '107', name: 'Altos da Vl. Paiva / Av. Eng. Francisco José Longo', sourceUrl: 'https://sjc.sp.gov.br/media/2lqlvjsz/107-77_site.pdf' },
  { code: '108', name: 'Canindu / via Vl. Cândida / Rodoviária', sourceUrl: 'https://sjc.sp.gov.br/media/rn4guygf/108-61_site.pdf' },
  { code: '111', name: 'Vale dos Pinheiros / Monte Castelo', sourceUrl: 'https://sjc.sp.gov.br/media/bq0hbm30/111-34_site.pdf' },
  { code: '112', name: 'Vl. Terezinha / CTA', sourceUrl: 'https://sjc.sp.gov.br/media/2cnpdxll/112-34_site.pdf' },
  { code: '115', name: 'Vl. Dirce / Altos de Santana / Av. Eng. Francisco José Longo', sourceUrl: 'https://sjc.sp.gov.br/media/tctjoqng/115-59_site.pdf' },
  { code: '116', name: 'Taquari / Rodoviária', sourceUrl: 'https://sjc.sp.gov.br/media/ftblbntd/116-52_site.pdf' },
  { code: '117', name: 'Morumbi / Aquarius', sourceUrl: 'https://sjc.sp.gov.br/media/4iflikxq/117-44e_site.pdf' },
  { code: '118', name: 'Alimentadora Sertãozinho / Alto da Ponte', sourceUrl: 'https://sjc.sp.gov.br/media/hxcfckhb/118-11_site.pdf' },
  { code: '119', name: 'Colonial / Aquarius', sourceUrl: 'https://sjc.sp.gov.br/media/cbintnbi/119-56_site.pdf' },
  { code: '121', name: 'Urbanova / Esplanada / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/p3hopbuu/121-69_site.pdf' },
  { code: '122', name: 'Altos de Santana / Parque Industrial', sourceUrl: 'https://sjc.sp.gov.br/media/kjpace4v/122-60_site.pdf' },
  { code: '124', name: 'Buquirinha II / Av. Eng. Francisco José Longo', sourceUrl: 'https://sjc.sp.gov.br/media/pw5e3a0k/124-35_site.pdf' },
  { code: '128', name: 'Urbanova-Colinas / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/i55nc41g/128-42_site.pdf' },
  { code: '130', name: 'Alimentadora São Francisco Xavier / São José dos Campos', sourceUrl: 'https://sjc.sp.gov.br/media/arfj2umx/130-18_site.pdf' },
  { code: '133', name: 'Alimentadora Nova República / Colonial', sourceUrl: 'https://sjc.sp.gov.br/media/5adcijlr/133-12_site.pdf' },
  { code: '134', name: 'Vale dos Pinheiros / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/bjzi1vf5/134-12_site.pdf' },
  { code: '135', name: 'Alimentadora Vale Sul Shopping / Center Vale Shopping', sourceUrl: 'https://sjc.sp.gov.br/media/cz3bajts/135-09e_site.pdf' },
  { code: '140', name: 'Altos de Santana / Av. Dr. João Guilhermino (circular no centro)', sourceUrl: 'https://sjc.sp.gov.br/media/hsukbot4/140-08_site.pdf' },
  { code: '141', name: 'Alimentadora São João-Sobrado / Alto da Ponte', sourceUrl: 'https://sjc.sp.gov.br/media/ejcfghea/141-14_site.pdf' },
  { code: '150', name: 'Vila Paiva / Corujão', sourceUrl: 'https://sjc.sp.gov.br/media/dw1oaweg/150-14_site.pdf' },
  { code: '160', name: 'Alimentadora Urbanova / Alphaville', sourceUrl: 'https://sjc.sp.gov.br/media/drhhlklt/160-11_site.pdf' },
  { code: '200', name: 'Alimentadora Pq. Tecnológico / Eugênio de Melo', sourceUrl: 'https://sjc.sp.gov.br/media/c3lp3mqu/200-32e_site.pdf' },
  { code: '201', name: 'Terminal Central / Bairrinho', sourceUrl: 'https://sjc.sp.gov.br/media/xa3pwcp4/201-64_site.pdf' },
  { code: '202', name: 'Bom Retiro / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/o3yipmds/202-59_site.pdf' },
  { code: '204A', name: 'Pq. Novo Horizonte / via Pedro A. Cabral', sourceUrl: 'https://sjc.sp.gov.br/media/idbbtyqu/204a-90_site.pdf' },
  { code: '204B', name: 'Pq. Novo Horizonte / via José Longo', sourceUrl: 'https://sjc.sp.gov.br/media/azmbhmwd/204b-87_site.pdf' },
  { code: '205', name: 'Eugênio de Melo / Galo Branco / Praça Afonso Pena', sourceUrl: 'https://sjc.sp.gov.br/media/h4afhbkh/205-76_site.pdf' },
  { code: '206', name: 'Jd. Santa Inês / via José Longo', sourceUrl: 'https://sjc.sp.gov.br/media/0s3hhltf/206-64_site.pdf' },
  { code: '208', name: 'Jd. Aeroporto / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/hmtevsyl/208-19_site.pdf' },
  { code: '209', name: 'Jd. Uirá / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/bobb3cnn/209-56_site.pdf' },
  { code: '210', name: 'Alimentadora Jd. Diamante / Vila Industrial', sourceUrl: 'https://sjc.sp.gov.br/media/jwjfusrf/210-45_site.pdf' },
  { code: '211', name: 'Jd. Califórnia / via Vista Verde / Santana / via Vl. Cristina', sourceUrl: 'https://sjc.sp.gov.br/media/ohflbtus/211-47e_site.pdf' },
  { code: '212', name: 'Putim / Terminal Central - via Av. dos Astronautas', sourceUrl: 'https://sjc.sp.gov.br/media/idglljni/212-75_site.pdf' },
  { code: '214', name: 'Vl. Tesouro / Sebastião Gualberto / Av. Eng. Francisco José Longo', sourceUrl: 'https://sjc.sp.gov.br/media/2tgiiiop/214-32_site.pdf' },
  { code: '215', name: 'Vl. Tesouro / Jd. Aquárius', sourceUrl: 'https://sjc.sp.gov.br/media/qnvcmuij/215-39_site.pdf' },
  { code: '219', name: 'Jd. Santa Luzia / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/pdcpfcxq/219-27_site.pdf' },
  { code: '222', name: 'Galo Branco / Jd. Aquárius', sourceUrl: 'https://sjc.sp.gov.br/media/asvble5i/222-12_site.pdf' },
  { code: '225', name: 'Galo Branco / Av. São José - semiexpressa', sourceUrl: 'https://sjc.sp.gov.br/media/lo4ckpc0/225-05e_site.pdf' },
  { code: '229', name: 'Terminal Central / Jd. Uirá - via Pedro A. Cabral', sourceUrl: 'https://sjc.sp.gov.br/media/z33pmf5e/229-16_site.pdf' },
  { code: '230', name: 'Vl. do Tesouro / Jd. Colonial', sourceUrl: 'https://sjc.sp.gov.br/media/4rwn4e1k/230-38_site.pdf' },
  { code: '231', name: 'Vl. do Tesouro / Vl. Dirce', sourceUrl: 'https://sjc.sp.gov.br/media/il5moloh/231-42_site.pdf' },
  { code: '232', name: 'Pq. Novo Horizonte / Av. São José (circular no centro)', sourceUrl: 'https://sjc.sp.gov.br/media/ljxbbh2o/232-19e_site.pdf' },
  { code: '237', name: 'Pq. Novo Horizonte / Jd. Aquárius', sourceUrl: 'https://sjc.sp.gov.br/media/xefagfym/237-49_site.pdf' },
  { code: '240', name: 'Pq. Novo Horizonte / Campo dos Alemães', sourceUrl: 'https://sjc.sp.gov.br/media/2l5koese/240-43_site.pdf' },
  { code: '242', name: 'Majestic / Praça Afonso Pena', sourceUrl: 'https://sjc.sp.gov.br/media/odsdno21/242-49_site.pdf' },
  { code: '243', name: 'Santa Maria / José Longo - via Jd. São José, Coqueiro e Frei Galvão', sourceUrl: 'https://sjc.sp.gov.br/media/zlxfl23i/243-23_site.pdf' },
  { code: '244', name: 'Jardim São José / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/oorojwky/244-33_site.pdf' },
  { code: '246', name: 'Alimentadora Dom Bosco / Tancredo Neves - via Santa Helena', sourceUrl: 'https://sjc.sp.gov.br/media/hywczwad/246-18_site.pdf' },
  { code: '250', name: 'Pq. Novo Horizonte Corujão', sourceUrl: 'https://sjc.sp.gov.br/media/do5aardp/250-16_site.pdf' },
  { code: '251', name: 'Eugênio de Melo Corujão', sourceUrl: 'https://sjc.sp.gov.br/media/2wyohq2d/251-15_site.pdf' },
  { code: '252', name: 'Jd. Uirá Corujão', sourceUrl: 'https://sjc.sp.gov.br/media/moxfnvd2/252-15_site.pdf' },
  { code: '300', name: 'Alimentadora Colonial / Ch. Reunidas', sourceUrl: 'https://sjc.sp.gov.br/media/yrbn5u0k/300-36_site.pdf' },
  { code: '302', name: 'Putim - via Tamoios / Praça Afonso Pena', sourceUrl: 'https://sjc.sp.gov.br/media/ipxlaim5/302-60_site.pdf' },
  { code: '303', name: 'Colonial / Rodoviária', sourceUrl: 'https://sjc.sp.gov.br/media/dyvcd0po/303-70_site.pdf' },
  { code: '304', name: 'Colonial / Praça Afonso Pena', sourceUrl: 'https://sjc.sp.gov.br/media/ppubi5y1/304-71_site.pdf' },
  { code: '305', name: 'Jd. São Judas Tadeu / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/v0cdcjtu/305-67_site.pdf' },
  { code: '306', name: 'Limoeiro - Dutra / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/14wdykcf/306-37_site.pdf' },
  { code: '307A', name: 'Morumbi / Terminal Central – via Anel Viário', sourceUrl: 'https://sjc.sp.gov.br/media/rdyobtug/307a-62_site.pdf' },
  { code: '307B', name: 'Alimentadora Morumbi / Satélite – via Av. Andrômeda', sourceUrl: 'https://sjc.sp.gov.br/media/awtn0wra/307b-60_site.pdf' },
  { code: '308', name: 'Terminal Central / Bq. dos Eucaliptos - Andrômeda', sourceUrl: 'https://sjc.sp.gov.br/media/onpl5ko4/308-62_site.pdf' },
  { code: '309', name: 'Pq. Industrial / Rodoviária', sourceUrl: 'https://sjc.sp.gov.br/media/2skjruay/309-38_site.pdf' },
  { code: '310', name: 'Residencial União - via Jd. Oriente / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/kmskoofw/310-59_site.pdf' },
  { code: '311', name: 'Limoeiro / Jd. das Indústrias / Praça Afonso Pena', sourceUrl: 'https://sjc.sp.gov.br/media/5gkgcllm/311-52_site.pdf' },
  { code: '313', name: 'Aquárius-Colinas / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/l3olo4qf/313-26_site.pdf' },
  { code: '314', name: 'Ch. Reunidas / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/ubidmfz0/314-29_site.pdf' },
  { code: '315', name: 'Parque Interlagos / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/to1k2xyc/315-62_site.pdf' },
  { code: '316', name: 'Torrão de Ouro - Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/kvhpebt5/316-37_site.pdf' },
  { code: '317', name: 'Campo dos Alemães - Rodoviária', sourceUrl: 'https://sjc.sp.gov.br/media/vt3bp5ve/317-54_site.pdf' },
  { code: '318', name: 'Terminal Central / D. Pedro I', sourceUrl: 'https://sjc.sp.gov.br/media/q41igp5e/318-52e_site.pdf' },
  { code: '319', name: 'Rodoviária / D. Pedro I', sourceUrl: 'https://sjc.sp.gov.br/media/txrlc3mg/319-42_site.pdf' },
  { code: '320', name: 'Pq. Industrial - Jd. das Indústrias / Praça Afonso Pena', sourceUrl: 'https://sjc.sp.gov.br/media/zdkjrame/320-47_site.pdf' },
  { code: '321', name: 'Alimentadora Campo dos Alemães / Jardim Satélite', sourceUrl: 'https://sjc.sp.gov.br/media/amadevhn/321-05_site.pdf' },
  { code: '322', name: 'Capuava / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/fe2fporj/322-29_site.pdf' },
  { code: '323', name: 'Campo dos Alemães / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/udmkq332/323-53_site.pdf' },
  { code: '325', name: 'Alimentadora Bosque dos Ipês / Jardim Satélite (via Jd. Sul)', sourceUrl: 'https://sjc.sp.gov.br/media/0vhljgwl/325-17e_site.pdf' },
  { code: '326', name: 'Alimentadora Residencial União / Estação Sul', sourceUrl: 'https://sjc.sp.gov.br/media/ijiihsr4/326-02_site.pdf' },
  { code: '327', name: 'Residencial União / Praça Afonso Pena', sourceUrl: 'https://sjc.sp.gov.br/media/apqjyvrp/327-31_site.pdf' },
  { code: '331', name: 'Campo dos Alemães / Aquárius', sourceUrl: 'https://sjc.sp.gov.br/media/rhcl3cad/331-41_site.pdf' },
  { code: '333', name: 'Jd. Santa Rosa - via São Judas e Colinas / Terminal Central - semiexpressa', sourceUrl: 'https://sjc.sp.gov.br/media/w00cta0j/333-13_site.pdf' },
  { code: '334', name: 'Jd. São Judas Tadeu / Terminal Central via Tecnasa', sourceUrl: 'https://sjc.sp.gov.br/media/w0jh5t5c/334-05_site.pdf' },
  { code: '335', name: 'Vila Adriana-EMHA II / Praça Afonso Pena', sourceUrl: 'https://sjc.sp.gov.br/media/cyml5lkk/335-06_site.pdf' },
  { code: '339', name: 'Alimentadora Dom Pedro / Estação Sul', sourceUrl: 'https://sjc.sp.gov.br/media/q4ipkbbz/339-02_site.pdf' },
  { code: '340', name: 'Eco Campos de São José / via Cambuí / Centro', sourceUrl: 'https://sjc.sp.gov.br/media/25inxa1q/340-14_site.pdf' },
  { code: '341A', name: 'Eco Campos de São José / Terminal Central', sourceUrl: 'https://sjc.sp.gov.br/media/prlkxt5h/341-22_site.pdf' },
  { code: '341B', name: 'Eco Campos de São José / Av. Eng. Francisco José Longo', sourceUrl: 'https://sjc.sp.gov.br/media/prlkxt5h/341-22_site.pdf' },
  { code: '342', name: 'Alimentadora Pousada do Vale / Eco - Campos de São José', sourceUrl: 'https://sjc.sp.gov.br/media/ehvffgsn/342-17_site.pdf' },
  { code: '343', name: 'Alimentadora Serrote / Eco - Campos de São José', sourceUrl: 'https://sjc.sp.gov.br/media/qxbjagvs/343-18_site.pdf' },
  { code: '344', name: 'Alimentadora Campos de São José / Eco Campos de São José', sourceUrl: 'https://sjc.sp.gov.br/media/bs5nqj4d/344-18_site.pdf' },
  { code: '345', name: 'Alimentadora Mariana II / Santa Cecília II', sourceUrl: 'https://sjc.sp.gov.br/media/pm2dajte/345-15_site-1.pdf' },
  { code: '349', name: 'Alimentadora Monterrey / Eco - Campos de São José', sourceUrl: 'https://sjc.sp.gov.br/media/drkczyfi/349-07_site.pdf' },
  { code: '350', name: 'Corujão Colonial', sourceUrl: 'https://sjc.sp.gov.br/media/qjtbjay3/350-12_site.pdf' },
  { code: '500', name: 'Aeroporto / Hotéis', sourceUrl: 'https://sjc.sp.gov.br/media/1uohacyh/500-03_site.pdf' },
];
